keys:
  - &admin_daffa age1ezf4gek368sta9vw6wfgvfyltkrrc86nf8msqcam2nwvplu2q39q426j6l
  - &control_plane age1rp7djn2d3cc8mywll2p28ctpna79d93rryzhgfqln48tglva95tsn00x3j
  - &cpu_worker_1 age1vgttjctzexuf86nrvfkl438tgr605umd9yfv86uzzxtw23c0t3psw7glj3
  - &gpu_worker_1 age1l04rpwtzulgmagkqemqewyra9dzddpq2qsq4c74nt9p33crvmsmsuqcxxg

creation_rules:
  - path_regex: secrets/control-plane\.yaml$
    key_groups:
      - age:
          - *admin_daffa
          - *control_plane

  - path_regex: secrets/cpu-worker-1\.yaml$
    key_groups:
      - age:
          - *admin_daffa
          - *cpu_worker_1

  - path_regex: secrets/gpu-worker-1\.yaml$
    key_groups:
      - age:
          - *admin_daffa
          - *gpu_worker_1

  - path_regex: secrets/default\.yaml$
    key_groups:
      - age:
          - *admin_daffa
